### ISSUE TITLE
[1.18/2.0] World does not render beyond a certain point

### ISSUE THREAD

**Issue by TwelvianZeta** [TwelvianZeta/ZetaForged#10]
As you can see in this screenshot, the world refuses to render beyond approximately 128-256 blocks away from spawn.
![2021-07-13_18 28 41](https://user-images.githubusercontent.com/40839581/125534932-6d812fff-6a8f-4ff6-b987-748cb3b9a93b.png)

**Comment by PercyDan54** [comment]
You may want to add these in ServerPlayNetworkHandler

IDK if it works

```Java
    @Inject(method = "clampHorizontal", at = @At("RETURN"), cancellable = true)
    private static void clampHorizontal(double d, CallbackInfoReturnable<Double> cir) {
        cir.setReturnValue(d);
    }

    @Inject(method = "clampVertical", at = @At("RETURN"), cancellable = true)
    private static void clampVertical(double d, CallbackInfoReturnable<Double> cir) {
        cir.setReturnValue(d);
    }
```

**Comment by TwelvianZeta** [comment]
I'ma close this issue because this apparently is due to a corrupted world.
